### ISSUE TITLE
RTL logic is not applied when the cell uses the `.subtitle` style

### ISSUE THREAD

**Issue by danielsaidi** [danielsaidi/Sheeeeeeeeet#113]
If you apply RTL to an action sheet, it doesn't affect cells that use the `.subtitle` style.

**Comment by danielsaidi** [comment]
![image](https://user-images.githubusercontent.com/429927/66697719-8c277d00-ecd8-11e9-8046-5eba432e7c40.png)

**Comment by mohammadghk** [comment]
I can fix that. But I think the correct logic should also change cell `semanticContentAttribute` so that the whole objects ( `imageView`, ... ) direction changes to right to left like this :

![Screen Shot 2019-10-13 at 11 19 17 AM](https://user-images.githubusercontent.com/20819422/66712570-6323ec80-edab-11e9-895d-7ef9728b8ad8.png)

So my question is should I make a difference between this and just changing `textLabel`'s alignment?
or just setting the alignment to right to left should change the whole direction?. Basically I'm asking is there a possibility that someone needs to change text alignment to RTL without changing the whole thing?

The only problem will remain is `.center` alignment for cells with `.subtitle` style which can be fixed by adding labels' constraints to correct anchors

**Comment by mohammadghk** [comment]
This problem happened because In `.subtitle` style label's are aligned to left anchor of the cell (or `imageView` if it's present) and their size depends on the text so `.right` or `.center` had no effect on them because the label's trailing was not attached to cells trailing. Its actually the default behavior of `UITableViewCell` !
So here is the result for `.center` after fix
![Screen Shot 2019-10-13 at 4 00 13 PM](https://user-images.githubusercontent.com/20819422/66715659-a180d200-edd2-11e9-95e5-023c6a38d0ce.png)

**Comment by danielsaidi** [comment]
If the semantic approach alone solves this, I think that would be so much better (and more correct) than having to set text alignment. I’ll look into this and your PR later today.

**Comment by mohammadghk** [comment]
Thanks a lot for your quick response 🙏

**Comment by danielsaidi** [comment]
Sorry for the delay, I've been sick and also working on another project. I'll look at this asap.

**Comment by danielsaidi** [comment]
I think that the bug fix in 3.1.3 will solve this problem.
