### ISSUE TITLE
App Extension Compatibility Request

### ISSUE THREAD

**Issue by james-ff** [danielsaidi/Sheeeeeeeeet#129]
Hello,

Would much work be required to enable this library to work in the context of an app extension?
- For example in a Share Extension or Action Extension
- https://developer.apple.com/app-extensions/

I have tried to add this as a pod to my app's share extension target, but on running the share extension it crashed with a runtime issue. I believe it has something to do with the AppDelegate not being present in this context.

Many Thanks,

James

**Comment by danielsaidi** [comment]
Hi! Sure, I guess it would be possible, but I think some features like the custom action sheet will behave strangely, since it's intended to use the entire screen. That won't be possible for many extensions, e.g. custom keyboard extensions.

However, you should be able to use the models. The library doesn't depend on there being an app delegate, so I suspect that it's rather some framework linking problems that cause the crash.

**Comment by james-ff** [comment]
Mainly interested in the share extension context myself. There you have a window context 
(I believe) similar to a fullscreen app.

**Comment by danielsaidi** [comment]
Hmmm...I can imagine that share extensions are limited in what they can do, but it shouldn't crash. Do you have any crash details?

**Comment by james-ff** [comment]
Forked this project and created a simple share extension demo, seems to work for me, I will check my main project again to see what the issue there is.

**Comment by danielsaidi** [comment]
Did you get it to work? I'd love to hear what was causing the crash.
