### ISSUE TITLE
Impossible to create Action Sheets identical to system

### ISSUE THREAD

**Issue by flagoworld** [danielsaidi/Sheeeeeeeeet#143]
- There seems to be no way to add a UIVisualEffectView and thus no way to make action sheets identical to the system ones.
- The default action sheet appearance does not at all match the system appearance.
- The show animation is very different and choppy compared to the system animation

I am quite surprised, as I would expect the default to be as close to the same as the system appearance as possible. Highly recommend making the above changes. May just be me, but I do suspect that most people who are looking at third party libraries to be able to customize UIAlertController more are doing so with the intent of starting at a system appearance and tweaking the appearance from there. Or, in my case, not tweaking the appearance at all but adding some custom views for buttons.

**Comment by danielsaidi** [comment]
This library is a few years old, and since Apple are moving away from the old action sheets into modern tools like context menus, modal sheets, menus etc. and new UI frameworks like SwiftUI, I have started to transition to those technologies. I will thus not put any time into refining the custom sheet parts of this library, but will happily review any PRs that can make the experience more closely resembling the system look & feel.
