### ISSUE TITLE
Sheeeeeeeeet on iPhone in Landscape Mode

### ISSUE THREAD

**Issue by giofid** [danielsaidi/Sheeeeeeeeet#2]
Hi Daniel,
your library looks very great (it's really a nice job!!) and I'm considering to use it in my app. 
I need to show until 8 options in actionsheet, so, to try, I modified `foodOptions()` function in `SheeeeeeeeetExample` like this
```
func foodOptions() -> [FoodOption] {
    return [.fast, .light, .homeMade, .fancy, .none, .fast, .light, .none]
}
```
and this is how action sheet appear on iPhone 7 simulator in **landscape** mode
![simulator screen shot - iphone 7 - 2017-12-19 at 12 30 42](https://user-images.githubusercontent.com/13570450/34155154-837c65d2-e4b8-11e7-8583-54e237943de7.png)
I think in this case the action sheet should be able to scroll so that any option can be available (like **Dropbox** iOS app or Google **Drive** iOS app, for example).

Thanks,
Giorgio

**Comment by danielsaidi** [comment]
Hi Giorgio,

Thank you so much, happy to hear that you like it!

Yeah, scrolling is something I have yet to solve. I considered adding it from the get go, but decided that given the 7 item rule of thumb (https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two) I decided to wait until someone requested support for more than 7 items :)

I think it's a pretty easy fix, but I won't have time to look at it until after the Christmas holidays.

**Comment by giofid** [comment]
Ok,
I look forward to this fix.

Have a great Christmas break.

**Comment by danielsaidi** [comment]
Hi again! I just wanted to let you know that I haven't forgotten about this issue :) I will take a look at it asap, but am wondering whether the entire sheet should scroll, or just the item section.

**Comment by giofid** [comment]
Hi daniel,
thank you!!!

If I remember correctly, `UIAlertController` (in `actioSheet` style) of `UIKit` framework scrolls only the items section. You could provide both mechanisms and leave the choice to the user by an appearance property, if you like.

**Comment by danielsaidi** [comment]
Hi Giorgio!

I am happy to say that I think that I found a clean solution for this. 

The action sheet will now check the available item height and enable item scrolling if the available item height is less than the required height.

The fix is available in `0.6.1`, which I am pushing up right now. Please try it out and let me know if it works for you.

**Comment by danielsaidi** [comment]
I also realize that people should perhaps also be given the choice to hide the header view in landscape. I add that as a separate enhancement issue.

**Comment by Hanfrey** [comment]
Can anyone confirm? For me it seems not to work. Version 0.6.2 installed. iPad on 10.3

**Comment by danielsaidi** [comment]
It works for me on simulator and on my real iPhone X. The action sheet does not show scrollbars (maybe it should?) but if I have too many items, I can scroll the item section.

**Comment by Hanfrey** [comment]
Yes, iPhone works. iPad not.

**Comment by danielsaidi** [comment]
I'll have a look at it when I wrap up some other projects.

**Comment by danielsaidi** [comment]
@Hanfrey Could you please provide me with a screenshot of the action sheet you try to get working on iPad? If it doesn't fit an iPad screen in popover, you must use a lot of options, right?

**Comment by danielsaidi** [comment]
Hi again! Since I haven't heard back in a while and I can confirm that this works on iPad (the entire sheet gets a scroller if you have many items in the sheet), I will close this issue.

To test this, add `items = items + items + items` in any test action sheet. However, the sheet should indicate that it can be scrolled. This is a bit hidden if the sheet is presented from a cell in the middle of the screen, on an iPad in landscape.
