### ISSUE TITLE
Tap behavior .none but still highlight on tap

### ISSUE THREAD

**Issue by VSG24** [danielsaidi/Sheeeeeeeeet#41]
I need to execute my own actions when a `ActionSheetCustomButton` is tapped (opening a modal). At the moment I have to set the `tapBehavior` for the button to `.none` otherwise the default value `.dismiss` causes the sheet to close when tapped however `.none` seems to disable the highlight color and that's not what I want.

**Comment by danielsaidi** [comment]
Hi!

I just changed this behavior a few weeks back, since I noticed that `tapBehavior` `.none` caused highlighting to be disabled even for tappable items.

The reason to why I added this in the first place was so that title items shouldn't highlight when they were tapped. However, as I made more items use `.none`, this didn't work.

So, I instead made the title items disable highlight for their cells, and removed this for the tap behavior. Could you please try the latest version of Sheeeeeeeeeeeeeeeeeeeeeeet and see if it works?

All the best

Daniel

**Comment by VSG24** [comment]
I can confirm that the latest version works fine.
