### ISSUE TITLE
[Bug] Sheet postion wrong in iPad when switch orientation of device

### ISSUE THREAD

**Issue by hangocanh2303** [danielsaidi/Sheeeeeeeeet#57]
when device rotate in two orientation: landscape and portrait, sheet position place wrong postion

**Comment by danielsaidi** [comment]
Which version do you use? Also, is the source view still on screen after the rotation?

If you can, please provide screenshots.

**Comment by danielsaidi** [comment]
Thank you for the screenshots! I will look at this asap.

**Comment by danielsaidi** [comment]
This happens when the source view disappears beyond the screen bounds after an orientation change. I'm not sure how to solve this without dismissing the popover.

**Comment by danielsaidi** [comment]
Hi again. I have decided to solve this bug by closing the action sheet after a screen orientation, if the source view is no longer visible on screen. I think this is valid, since you wouldn't have been able to open the sheet since the view is not visible. This will be out in `1.2.4`.

**Comment by danielsaidi** [comment]
This is fixed in `1.3.0`, with a change to the default popover presenter behavior. From now on, these presenters will by default hide the popover when the orientation changes. This is described in detail in the [release notes](https://github.com/danielsaidi/Sheeeeeeeeet/releases/tag/1.3.0).

You can disable this behavior and also override the default orientation change handling, so I hope you can use this to solve your problem.

I also want to thank you for posting this issue, since it made me discover an even more severe bug. For table and collection views, due to their cell reuse, the popover could point to a completely different cell after an orientation. The cell instance would be the same, but depending on the reuse, it could present something entirely different. Hiding the popover was the easiest way to solve this bug.
