### ISSUE TITLE
Some problems on iPad

### ISSUE THREAD

**Issue by giofid** [danielsaidi/Sheeeeeeeeet#7]
Hi Daniel,
I'm running into some trouble using your library on iPad. First, I see an annoying flickering when I put app in background with a `Sheeeeeeeeet` opened menu and take it in foreground again . To reproduce it

1. Run Demo
2. Open a menu (tap on standard row, for example)
3. Put app in background
4. Take it in foreground again

Second, in the demo app, when I open Standard menu and I tap a menu item no alert appears. In the console I see

> SheeeeeeeeetExample[8754:168099] Warning: Attempt to present <UIAlertController: 0x7fdabd04f400>  on <SheeeeeeeeetExample.ViewController: 0x7fdabbc06b10> which is already presenting (null)

Thanks,
Giorgio

**Comment by danielsaidi** [comment]
Hi Giorgio!

Thank you for reaching out! I'll take a look at the flickering asap.

Regarding the alert, I see it too. The reason for this is that the example app tries to alert while the popover is still presented. It just requires a quick fix...will look at it asap.

**Comment by giofid** [comment]
Thank you Daniel!

To solve the alert problem I moved `_self.itemSelectAction(_self, item)` in `itemTapAction` func of `ActionSheet` class after `_self.dismiss()`.

```
open lazy var itemTapAction: ActionSheetItemTapAction = {
    return { [weak self] item in
        guard let _self = self else { return }
        _self.reloadData()
         if item.tapBehavior == .dismiss {
               _self.dismiss()
         }
         _self.itemSelectAction(_self, item)
    }
}()
```
But I don't know if it's the right way to fix it.

**Comment by danielsaidi** [comment]
Nice! However, I think I'll make the presenter dismiss async so we can trigger the action once the dismissal is done. I had to do this manual fiddling in another project that uses Sheeeeeeeeet as well, so it's better to improve the library design instead.

**Comment by danielsaidi** [comment]
Hi again,

I have fixed a bunch of stuff and bumped Sheeeeeeeeet to `0.6.0`, so I'd love for you tro try it out.

Regarding the bugs above, I have solved them like this:

1. The flickering appears when a popover is presented when the app is opened from the background. I have solved this by letting the iPad presenter (the only one that uses a popover) dismiss the action sheet whenever the app is sent to the background. I think it's an ok solution, although removing the flickering would naturally be even better.

2. The warning you saw was because the example app tried to present an alert while a popover was presented. I have solved this by making the dismiss function async. The popover presenter will now wait until the sheet is fully dismissed before it calls the select action.

I hope this helps you out.
