### ISSUE TITLE
Highlight colors

### ISSUE THREAD

**Issue by narek-sv** [danielsaidi/Sheeeeeeeeet#70]
add please `highlightBackgroundColor` property to appearance

**Comment by danielsaidi** [comment]
Hi @narek-sv, sorry for the slow reply! Is this still an issue for you?

Sheeeeeeeeet's cells are basic table view cells, so you can just use the already existing api:s for this, for instance https://stackoverflow.com/questions/2553746/how-to-change-the-blue-highlight-color-of-a-uitableviewcell

Is this sufficient for you or do you still think that it should go into the appearance model?

**Comment by danielsaidi** [comment]
I'd prefer not to venture down that road, since that would open up for all sorts of stuff that should be handled with the appearance proxies. I'd suggest that you subclass `ActionSheet` and implement this yourself. It's really easy: https://stackoverflow.com/questions/26895370/uitableviewcell-selected-background-color-on-multiple-selection
